<h3>Задание 1</h3><br>

Исходный код взят из моего GitHub: https://github.com/StarPassage/MathMethods/blob/main/Task7.ipynb

In [2]:
import numpy as np
import pandas as pd
from scipy.optimize import Bounds, linprog
np.set_printoptions(suppress=True)

In [11]:
C = np.array([list(map(int, input(f'Введите {i+1} строку матрицы C (числа через пробел):\n').split())) for i in range(3)])
print('\nМатрица C:')
print(C)

Введите 1 строку матрицы C (числа через пробел):
5 7 9 7 0
Введите 2 строку матрицы C (числа через пробел):
10 14 13 23 0
Введите 3 строку матрицы C (числа через пробел):
11 18 12 14 0

Матрица C:
[[ 5  7  9  7  0]
 [10 14 13 23  0]
 [11 18 12 14  0]]


In [4]:
a1, a2, a3 = map(int, input('Введите через пробел числа a1, a2, a3:\n').split())

Введите через пробел числа a1, a2, a3:
110 60 280


In [5]:
A = np.array([a1, a2, a3])

In [29]:
b1, b2, b3, b4 = map(int, input('Введите через пробел числа b1, b2, b3, b4, b5:\n').split())

Введите через пробел числа b1, b2, b3, b4, b5:
130 30 100 160


In [30]:
B = np.array([b1, b2, b3, b4])

In [31]:
N = len(A)
M = len(B)

In [32]:
if sum(A) == sum(B):
    print('Задача закрытого типа')
else:
    print('Задача открытого типа')

Задача открытого типа


In [36]:
b5 = 30
B = np.append(B, b5)

In [37]:
df = pd.DataFrame(C, columns=B, index=A)
df.columns.name = 'aᵢ \\ bⱼ'
df

aᵢ \ bⱼ  130  30   100  160  30 
110        5    7    9    7    0
60        10   14   13   23    0
280       11   18   12   14    0

Допустимый план перевозки груза методом минимальной стоимости

In [39]:
P = np.zeros_like(C)
INF = 1_000_000_007
C_ = C.copy()
A_ = A.copy()
B_ = B.copy()
i = 0
j = 0
while not np.all(C_ == INF):
    i, j = np.unravel_index(C_.argmin(), C_.shape)
    P[i][j] = min(A_[i], B_[j])
    if A_[i] <= B_[j]:
        C_[i].fill(INF)
        B_[j] -= A_[i]
        A_[i] = 0
    else:
        C_[:, j].fill(INF)
        A_[i] -= B_[j]
        B_[j] = 0    

F = 0
for i in range(N):
    for j in range(M):
        F += C[i][j] * P[i][j]
print('Полученный план перевозки груза:\n', P)
print('Значение целевой функции для этого опорного плана F =', F)

Полученный план перевозки груза:
 [[ 80   0   0   0  30]
 [ 50  10   0   0   0]
 [  0  20 100 160   0]]
Значение целевой функции для этого опорного плана F = 4840
